project_id = "sqdjteugxarustivcpqs"

[functions.proxy-generate-recipes]
verify_jwt = false

[functions.ai-shopping-agent]
verify_jwt = true

[functions.price-lookup]
verify_jwt = true

[functions.unified-price-lookup]
verify_jwt = false
