// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqdjteugxarustivcpqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZGp0ZXVneGFydXN0aXZjcHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTAzMTUsImV4cCI6MjA2MzY4NjMxNX0.X0vIPd4bU8Gbq75xAtyQs1u2LeiG7uxXAxq1XrGvV2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);